### ISSUE TITLE
[Lifecycle] Adapter fails to provision 0.7.1

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-kuma#104]
**Description**
<img width="1009" alt="Screen Shot 2020-10-07 at 11 03 19 PM" src="https://user-images.githubusercontent.com/7570704/95413581-6637b700-08f1-11eb-8262-6c547fd81a38.png">

**Comment by leecalcote** [comment]
Same issue with all versions of the service mesh.

**Comment by kushthedude** [comment]
Bug in the dockerfile again, fix on the way @leecalcote

**Comment by kushthedude** [comment]
@kumarabd You won't mind if I PR for this issue 🙂 ?

**Comment by leecalcote** [comment]
@kushthedude please do. :)

**Comment by kushthedude** [comment]
> @kushthedude please do. :)

Done sir :D
