### ISSUE TITLE
Adapter doesn't get initialized

### ISSUE THREAD

**Issue by kumarabd** [layer5io/meshery-kuma#146]
**Description**
Adapter initialisation fails with meshery. Below are the logs:
```
time="2021-04-05T21:36:32Z" level=info msg="Adaptor Listening at port: 10007" app=kuma-adaptor
time="2021-04-05T21:39:05Z" level=info msg="Creating instance" app=kuma-adaptor
time="2021-04-05T21:39:05Z" level=error msg="Error creating adapter instance.Error validating kubeconfig.none of the auth infos are valid either the certificate path is invalid or is inaccessible" app=kuma-adaptor code=1001 probable-cause=None severity=1 short-description=None suggested-remediation=None
```

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

**Comment by dhruv0000** [comment]
I was facing similar error while trying to use DOs kubeconfig. Does your kubeconfig resemble something like below.
```
users:
- name: do-blr1-k8s-do-admin
  user:
    token: 13asdf9u394vi.....
```
Updating `meshery-adapter-library` to `v0.1.13` should do the trick in that case.
