### ISSUE TITLE
Build failing: Remnants of Istio adapter code

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-kuma#26]
**Description**
This Kuma adapter was built using the Istio adapter as a template. The Kuma adapter build is failing given that some of the Istio code remains.

Build failure - https://github.com/layer5io/meshery-kuma/runs/279301685#step:4:119

**Expected Behavior**
The Istio references need changed or removed. Kuma adapter should build cleanly.

**Comment by ashiscs** [comment]
sir i addressed this issue
https://github.com/layer5io/meshery-kuma/pull/27
