### ISSUE TITLE
Add GitHub Star - Slack Notify workflow to this repo

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-kuma#45]

**Comment by morrme** [comment]
annd this one @leecalcote

**Comment by leecalcote** [comment]
Whoops. 😉 

https://github.com/layer5io/meshery-kuma/blob/master/.github/workflows/slack.yml

**Comment by leecalcote** [comment]
@morrme are you interested in:

- [ ] documentation, markdown, Jekyll,
- [ ] DevOps: Workflow building with GitHub Actions, Homebrew, Scoop, Docker, Kubernetes
- [ ] Javascript: React, NextJs, Billboardjs
- [ ] Golang
- [ ] Web: Gatbsy, Strapi,  html, css, animations
- [ ] Visual design: illustrator, photoshop, css or video animation

Ping in the Layer5 Slack, so we can fuel your passions. 😄

**Comment by morrme** [comment]
I am still coming up with a good answer to this. 

> * [ ]  documentation, markdown, Jekyll,
> * [ ]  DevOps: Workflow building with GitHub Actions, Homebrew, Scoop, Docker, Kubernetes
> * [ ]  Javascript: React, NextJs, Billboardjs
> * [ ]  Golang
> * [ ]  Web: Gatbsy, Strapi,  html, css, animations
