### ISSUE TITLE
[layer5io/meshery-kuma] update link to new welcome guide

### ISSUE THREAD

**Issue by ashiscs** [layer5io/meshery-kuma#6]
**Description**
A brief description of the issue.

**Expected Behavior**
A brief description of what you expected to happen.

**Screenshots**
Add screenshots, if applicable, to help explain your problem.

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

**Comment by leecalcote** [comment]
Fixed by #5
