### ISSUE TITLE
[UI] Confirm Kuma logo displays on meshery-kuma adapter

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-kuma#63]
**Current Behavior**
The Meshery adapter for Kuma has not been included into the default Meshery release as a beta adapter, yet. 

I haven't seen the Kuma adapter in-action as a container, yet, and so I'm not sure if this has already been addressed.

**Desired Behavior**
The Meshery adapter for Kuma should display a Kuma project logo on the adapter chip in the Meshery UI. Code changes will need to be completed in Meshery to ensure proper representation.

**Comment by leecalcote** [comment]
Related to https://github.com/layer5io/meshery/issues/1444

**Comment by kumarabd** [comment]
@leecalcote  This is addressed in here https://github.com/layer5io/meshery/issues/1522

**Comment by leecalcote** [comment]
Oh, very good.
