### ISSUE TITLE
Helm chart for Learn-Layer5

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-kuma#72]
Yes right, let me craete a helm chart for this, so that we can version them too.

_Originally posted by @kumarabd in https://github.com/layer5io/meshery-kuma/pull/71#discussion_r479001155_

**Comment by kumarabd** [comment]
https://github.com/layer5io/learn-layer5/pull/51
Unable to link as this is in another repository.

**Comment by leecalcote** [comment]
Completed.
