### ISSUE TITLE
Cut-down the adapter size to 30MB or other

### ISSUE THREAD

**Issue by Aisuko** [layer5io/meshery-kuma#91]
**Description**
A brief description of the issue.

As @leecalcote  said, that the Meshery adapter for Kuma is 300MB currently, 

**Expected Behavior**
A brief description of what you expected to happen.

We need to cut down the adapter size to 30MB

**Screenshots**
Add screenshots, if applicable, to help explain your problem.

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

**Comment by leecalcote** [comment]
@Aisuko thanks for this. 👍 

I think we're good to go now given an update that @kushthedude made recently - https://hub.docker.com/repository/docker/layer5/meshery-kuma/tags?page=1
